[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.75
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
normal=   { family= "JetBrainsMono Nerd Font" }
bold=     { family= "JetBrainsMono Nerd Font" }
italic=   { family= "JetBrainsMono Nerd Font" }
bold_italic= { family= "JetBrainsMono Nerd Font" }
size= 14

[colors.primary]
background= '#030315'
foreground= '#cdc7d3'

[colors.normal]
black=   '#19192D'
red=     '#553B88'
green=   '#364995'
yellow=  '#60559D'
blue=    '#9F6495'
magenta= '#CB7192'
cyan=    '#6398C6'
white=   '#cdc7d3'

[colors.bright]
black=   '#8f8b93'
red=     '#553B88'
green=   '#364995'
yellow=  '#60559D'
blue=    '#9F6495'
magenta= '#CB7192'
cyan=    '#6398C6'
white=   '#cdc7d3'
